# Travis continuous integration configuration file
language: python
python:
  - 3.6
  - 3.7
dist: xenial
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - pytest --cov=olxcleaner --cov-report=term-missing
after_success:
  - codecov
